server:
    port: 9092

spring:
    application:
        # 应用名称
        name: notify-server
    profiles:
        # 环境配置
        active: dev
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.2.201:8848
                group: DEFAULT_GROUP
                namespace: 21e021a4-2f24-43f8-8f01-0dfe1eef2c55
            config:
                server-addr: 192.168.2.201:8848
                namespace: 21e021a4-2f24-43f8-8f01-0dfe1eef2c55
                group: DEFAULT_GROUP
    config:
        import:
            - nacos:application-${spring.profiles.active}.yml?refreshEnabled=true
            - nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true

