server:
    port: 9091

spring:
    application:
        name: chat-others
    profiles:
        active: dev

    thymeleaf:
        servlet:
            content-type: text/html
            mode: HTML5
            prefix: classpath:/templates/
            suffix: .html
            cache: false
            enable-spring-el-compiler: false


